### ISSUE TITLE
How to show distance between user and destination

### ISSUE THREAD

**Issue by estherooi** [SayChunKim/BeyondAR-v2#1]
Hi, I'm new to AR. Is it possible to show the distance between user and the destination in m? How can I do it? 
Something like this. 

![Screenshot_20200408_202153](https://user-images.githubusercontent.com/61179834/78783761-ac887980-7993-11ea-90fe-7ec9535ed9a7.jpg)

**Comment by SayChunKim** [comment]
You will have to look at `app/src/main/java/com/beyondar/example` route in this repo (you may dive into that subdirectory of examples of Activities), you will find 2 related files:
1. **CustomWorldHelper.java** - Stores list of POIs locally. Can be recalled in other Activities.
2. **TourismGoPOIActivity.java** - Activity with CustomWorldHelper POIs, by default MaxDistanceToRender is 1000 (1km radius range), BeyondarLocationManager to get user's position

The distance between User and POI algorithm is defined in BeyondAR, just might not be called according the examples of activity (perhaps `SimpleCameraWithRadarActivity.java` is what you're looking for). May refer BeyondAR Documentation for more method references.

Cheers
